columns:
  - Time_spent_Alone: float
  - Stage_fear: object
  - Social_event_attendance: float
  - Going_outside: float
  - Drained_after_socializing: object
  - Friends_circle_size: float
  - Post_frequency: float
  - Personality: object


numerical_columns:
  - Time_spent_Alone
  - Social_event_attendance
  - Going_outside
  - Friends_circle_size
  - Post_frequency

categorical_columns:
  - Stage_fear
  - Drained_after_socializing
  

target_column: Personality

drop_columns: _id

# for data transformation
num_features:
  - Time_spent_Alone
  - Social_event_attendance 
  - Going_outside
  - Friends_circle_size 
  - Post_frequency

cat_features:
  - Stage_fear
  - Drained_after_socializing

